export function sanitizeTtsText(input: string): string {
  let text = String(input ?? '')
  text = text.replace(/\r\n/g, '\n')
  text = text.replace(/```[\s\S]*?```/g, '')
  text = text.replace(/`([^`]+)`/g, '$1')
  text = text.replace(/!\[([^\]]*)\]\((?:[^)]+)\)/g, '$1')
  text = text.replace(/\[([^\]]+)\]\((?:[^)]+)\)/g, '$1')
  text = text.replace(/^#{1,6}\s+/gm, '')
  text = text.replace(/^>\s?/gm, '')
  text = text.replace(/^\s*[-*+]\s+\[[xX ]\]\s+/gm, '')
  text = text.replace(/^\s*[-*+]\s+/gm, '')
  text = text.replace(/^\s*\d+\.\s+/gm, '')
  text = text.replace(/^\s*[-*_]{3,}\s*$/gm, '')
  text = text.replace(/<\/?[^>]+>/g, '')
  text = text.replace(/\*\*(.*?)\*\*/g, '$1')
  text = text.replace(/\*(.*?)\*/g, '$1')
  text = text.replace(/__(.*?)__/g, '$1')
  text = text.replace(/_(.*?)_/g, '$1')
  text = text.replace(/~~(.*?)~~/g, '$1')
  text = text.replace(/\|/g, ' ')
  text = text.replace(/[ \t]{2,}/g, ' ')
  text = text.replace(/\n{3,}/g, '\n\n')
  return text.trim()
}

