# -*- coding: utf-8 -*-
"""server-AI-MCS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J37KPSwpYoSYz9lhVJyYvSnACqleIXpG
"""

!pip install transformers accelerate sentencepiece bitsandbytes
!pip install TTS  # XTTS-v2
!pip install git+https://github.com/openai/whisper.git
!pip install torchvision pillow

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

CHAT_MODEL = "unsloth/Llama-3.2-3B"

chat_tokenizer = AutoTokenizer.from_pretrained(CHAT_MODEL)
chat_model = AutoModelForCausalLM.from_pretrained(
    CHAT_MODEL,
    torch_dtype=torch.float16,
    device_map="auto"
)

from transformers import LlavaNextForConditionalGeneration, AutoProcessor

VLM_MODEL = "llava-hf/llava-1.5-7b-hf"

vlm_processor = AutoProcessor.from_pretrained(VLM_MODEL)
vlm_model = LlavaNextForConditionalGeneration.from_pretrained(
    VLM_MODEL,
    torch_dtype=torch.float16,
    device_map="auto"
)

import whisper

stt_model = whisper.load_model("large-v3").to("cuda")

# @title 💊 Máy "Chữa Lành" Giọng Sóc Chuột (Full Code)
# 1. Cài đặt môi trường (Chạy ngầm để không rối mắt)
import os
print("⏳ Đang cài đặt thư viện... (Chờ xíu nhé)")
os.system("apt-get install -y ffmpeg > /dev/null")
os.system("pip install -q gTTS librosa soundfile")

import random
from gtts import gTTS
import librosa
import soundfile as sf
import numpy as np
from IPython.display import Audio, display

# --- 2. CẤU HÌNH NỘI DUNG & HIỆU ỨNG ---

# Danh sách các câu "liệu pháp tâm lý" hài hước
healing_quotes = [
    "A lô! Đừng áp lực nữa. Việc hôm nay chưa xong thì... mai làm. Trái đất vẫn quay mà!",
    "Hít vào thật sâu... Thở ra hết nỗi buồn... Chỉ giữ lại tiền và đồ ăn ngon thôi nhé.",
    "Bạn gì ơi, deadline chỉ là hư vô. Sức khỏe mới là vĩnh cửu. Đi ngủ sớm đi!",
    "Cố lên! Cuộc đời là những cú tát, nhưng mình có thể né mà. Cười lên cái xem nào!",
    "Alo tổng đài vũ trụ đây. Chúng tôi xác nhận bạn rất tuyệt vời, chỉ hơi thiếu ngủ chút thôi."
]

# Chọn ngẫu nhiên 1 câu
text_input = random.choice(healing_quotes)

# Cấu hình độ "Hài hước"
SPEED_RATE = 1.3  # Tốc độ ( > 1.0 là nhanh)
PITCH_STEPS = 5   # Độ cao ( > 0 là giọng trẻ con/sóc chuột)

# --- 3. XỬ LÝ CHÍNH ---

def create_funny_therapy(text):
    print(f"\n📝 Bot đang đọc: \"{text}\"")

    # B1: Tạo giọng gốc (Google TTS - Ổn định nhất)
    temp_file = "temp_voice.mp3"
    try:
        tts = gTTS(text=text, lang='vi')
        tts.save(temp_file)
    except Exception as e:
        print("❌ Lỗi kết nối Google. Kiểm tra lại mạng nhé.")
        return None

    # B2: Xử lý âm thanh (Biến giọng)
    try:
        # Load file
        y, sr = librosa.load(temp_file, sr=None)

        # Tăng tốc
        y_fast = librosa.effects.time_stretch(y, rate=SPEED_RATE)

        # Tăng tone
        y_funny = librosa.effects.pitch_shift(y_fast, sr=sr, n_steps=PITCH_STEPS)

        # Lưu file kết quả
        output_file = "giong_giam_stress.wav"
        sf.write(output_file, y_funny, sr)

        return output_file, sr
    except Exception as e:
        print(f"❌ Lỗi xử lý âm thanh: {e}")
        return None

# --- 4. CHẠY VÀ PHÁT ---

result = create_funny_therapy(text_input)

if result:
    file_path, rate = result
    print("\n(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧ Xong rồi! Mời bạn nghe liều thuốc tinh thần này:")
    display(Audio(file_path, rate=rate, autoplay=True)) # Tự động phát

# ==========================
# 📌 CELL 4 — FULL API SERVER
# ==========================

import base64
import uuid
import os
from io import BytesIO
from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
import asyncio
import json
import subprocess
from pydantic import BaseModel
from PIL import Image
import torch
from fastapi.responses import FileResponse

app = FastAPI(title="Medical Consultation GPU API", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==============================
# 🔶 REQUEST MODELS
# ==============================

class ChatMessage(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: list[ChatMessage]

class VisionChatRequest(BaseModel):
    text: str
    image_base64: str

class VisionMultiRequest(BaseModel):
    text: str
    images_base64: list[str]

class TextToSpeechRequest(BaseModel):
    text: str

class TextToSpeechStreamRequest(BaseModel):
    text: str


# ==============================
# 🔷 1) CHAT COMPLETION API
# ==============================

@app.post("/v1/chat")
async def chat_api(req: ChatRequest):

    user_msg = req.messages[-1].content

    inputs = chat_tokenizer(user_msg, return_tensors="pt").to("cuda")
    output = chat_model.generate(
        **inputs,
        max_new_tokens=256,
        temperature=0.7
    )

    text = chat_tokenizer.decode(output[0], skip_special_tokens=True)
    return {"reply": text}

@app.post("/v1/chat/completions")
async def chat_completions(req: ChatRequest):
    user_msg = req.messages[-1].content
    inputs = chat_tokenizer(user_msg, return_tensors="pt").to("cuda")
    output = chat_model.generate(
        **inputs,
        max_new_tokens=256,
        temperature=0.7
    )
    text = chat_tokenizer.decode(output[0], skip_special_tokens=True)
    return {
        "choices": [
            {
                "message": {
                    "role": "assistant",
                    "content": text
                }
            }
        ]
    }


# ==============================
# 🔶 2) VISION-LANGUAGE API (LLAVA)
# ==============================

@app.post("/v1/vision")
async def vision_api(req: VisionChatRequest):

    # Decode base64 → image
    image_bytes = base64.b64decode(req.image_base64)
    image = Image.open(BytesIO(image_bytes)).convert("RGB")

    inputs = vlm_processor(
        text=req.text,
        images=image,
        return_tensors="pt"
    ).to("cuda")

    output = vlm_model.generate(**inputs, max_new_tokens=256)
    text = vlm_processor.tokenizer.decode(output[0], skip_special_tokens=True)

    return {"reply": text}

@app.post("/v1/vision-multi")
async def vision_multi_api(req: VisionMultiRequest):
    replies = []
    for b64 in req.images_base64:
        image_bytes = base64.b64decode(b64)
        image = Image.open(BytesIO(image_bytes)).convert("RGB")
        inputs = vlm_processor(text=req.text, images=image, return_tensors="pt").to("cuda")
        output = vlm_model.generate(**inputs, max_new_tokens=256)
        t = vlm_processor.tokenizer.decode(output[0], skip_special_tokens=True)
        replies.append(t)
    return {"reply": "\n".join(replies)}


# ==============================
# 🔷 3) TEXT TO SPEECH (XTTS v2)
# ==============================

@app.post("/v1/tts")
async def tts_api(req: TextToSpeechRequest):

    file_id = uuid.uuid4().hex
    out_path = f"/content/{file_id}.wav"

    tts.tts_to_file(
        text=req.text,
        file_path=out_path
    )

    return {
        "audio_url": f"/files/{file_id}.wav"
    }

@app.post("/v1/tts/stream")
async def tts_stream_api(req: TextToSpeechStreamRequest):
    async def gen():
        text = req.text.strip()
        parts = []
        buf = []
        for ch in text:
            buf.append(ch)
            if len(buf) >= 180 or ch in ".!?\n":
                parts.append("".join(buf).strip())
                buf = []
        if buf:
            parts.append("".join(buf).strip())
        idx = 0
        for p in parts:
            file_id = uuid.uuid4().hex
            out_path = f"/content/{file_id}.wav"
            tts.tts_to_file(text=p, file_path=out_path)
            with open(out_path, "rb") as f:
                b = f.read()
            payload = {"chunk_id": idx, "audio_base64": base64.b64encode(b).decode("ascii")}
            idx += 1
            yield json.dumps(payload) + "\n"
            await asyncio.sleep(0)
    return StreamingResponse(gen(), media_type="application/json")


# Serve audio files
@app.get("/files/{filename}")
async def get_audio(filename: str):
    path = f"/content/{filename}"
    return FileResponse(path, media_type="audio/wav")

@app.get("/health")
async def health():
    return {"status": "ok"}


# ==============================
# 🔶 4) SPEECH TO TEXT (WHISPER)
# ==============================

@app.post("/v1/stt")
async def stt_api(file: UploadFile = File(...)):

    # Save uploaded file
    temp_path = "/content/input_audio.wav"
    with open(temp_path, "wb") as f:
        f.write(await file.read())

    # Transcribe using Whisper
    result = stt_model.transcribe(temp_path, language="vi")

    return {"text": result["text"]}

@app.post("/v1/stt/stream")
async def stt_stream_api(file: UploadFile = File(...)):
    temp_path = "/content/input_audio_stream.wav"
    with open(temp_path, "wb") as f:
        f.write(await file.read())
    full = stt_model.transcribe(temp_path, language="vi")
    text = full["text"]
    async def gen():
        tokens = text.split()
        cur = []
        for i, t in enumerate(tokens):
            cur.append(t)
            if len(cur) >= 12 or i == len(tokens) - 1:
                yield json.dumps({"partial": " ".join(cur)}) + "\n"
                cur = []
                await asyncio.sleep(0)
    return StreamingResponse(gen(), media_type="application/json")

@app.get("/gpu/metrics")
async def gpu_metrics():
    data = {}
    try:
        q = [
            "nvidia-smi",
            "--query-gpu=temperature.gpu,utilization.gpu,utilization.memory,memory.total,memory.used",
            "--format=csv,noheader,nounits",
        ]
        r = subprocess.run(q, capture_output=True, text=True)
        if r.returncode == 0:
            s = r.stdout.strip().split(",")
            data["gpu_temperature"] = float(s[0])
            data["gpu_utilization"] = float(s[1])
            data["mem_utilization"] = float(s[2])
            data["mem_total"] = float(s[3])
            data["mem_used"] = float(s[4])
    except Exception:
        pass
    return data


# ==============================
# 🔷 SERVER READY
# ==============================

print(f"🚀 API Ready! Chat / Vision / TTS / STT đang chạy trên PORT {PORT}")

# CELL 5 — START SERVER with PYNGROK (v2)

print("--- Khởi Chạy Server ---")

if IN_COLAB and USE_NGROK:
    try:
        token = NGROK_AUTH_TOKEN  # lấy từ cell 2
        if token:
            print("🔑 NGROK_AUTH_TOKEN đã sẵn sàng.")

            # Kill process cũ để tránh lỗi ERR_NGROK_105
            ngrok.kill()

            import threading, time
            def run_server():
                import uvicorn
                uvicorn.run(app, host="0.0.0.0", port=PORT)
            th = threading.Thread(target=run_server, daemon=True)
            th.start()
            time.sleep(1)

            # Mở tunnel cho PORT đã chọn
            public_url = ngrok.connect(PORT)
            print(f"✅ Server URL (Ngrok): {public_url.public_url}")
            print(f"👉 Copy URL này dán vào Agent.")
        else:
            print("❌ Không tìm thấy token")

    except Exception as e:
        print(f"⚠️ Lỗi Ngrok: {e}")
        print("⚠️ Server sẽ chạy Localhost")

else:
    print("🌐 Không chạy Colab hoặc USE_NGROK = False → Server chạy Localhost")